#!/bin/sh
PACKAGES=`find . -iname packages -not -path "*/node_modules/*" -not -path "*/.git/*"  -exec find {} -maxdepth 1 -mindepth 1  \;`
EXIT_STATUS=0

for PACKAGE in $PACKAGES
do
  if ! (cd $PACKAGE && $@); then
    EXIT_STATUS=1
  fi
done

exit $EXIT_STATUS
